### ISSUE TITLE
[QUESTION] Avoid embedding image assets in bundle

### ISSUE THREAD

**Issue by murtraja** [peter-jozsa/react-native-web-image-loader#7]
@peter-jozsa, this issue really is not directly related to this library so feel free to close this but I wanted to know how can one avoid the assets being merged into the bundle? 

I would like to decrease the bundle size by decoupling the static images from the bundle. Can you help me please. 

Please refer https://github.com/oblador/react-native-vector-icons/issues/980 for my configs

**Comment by peter-jozsa** [comment]
Hey there,

The problem is that you are using `url-loader` to process images in your webpack build:
```js
// This is needed for webpack to import static images in JavaScript files.
const imageLoaderConfiguration = {
  test: /\.(gif|jpe?g|png|svg)$/,
  use: {
    loader: 'url-loader',
    options: {
      name: '[name].[ext]'
    }
  }
};
```

In your case `url-loader` will always put files matching `/\.(gif|jpe?g|png|svg)$/` into your bundle as a dataURI. You can set the maximum file size for `url-loader` with the `limit` option (More info here: [https://github.com/webpack-contrib/url-loader#limit]())

**I suggest you not to use `url-loader` to bundle images, use `file-loader` instead:** [https://github.com/webpack-contrib/file-loader#getting-started]()

I hope I could help. Have a nice day!

**Comment by murtraja** [comment]
@peter-jozsa, thanks for the quick revert. Really appreciate your help. I think that makes sense. Thank you again for pointing that out
